trigger:
  - main

pool:
  # vmImage: 'ubuntu-latest'
  name: default

steps:
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: '$(jahangir842)/portal'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)
