version: '3'

services:
  web:
    build: .
    expose:
      - "5000"
    volumes:
      - ./static:/app/static
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/app/static
    depends_on:
      - web
