name: Deploy to Development

on:
  push:
    branches: [develop, main]
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: devops-rg
  CONTAINER_APP_NAME: portal
  DOCKER_IMAGE_NAME: jahangir842/portal

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy Infrastructure
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters/dev.parameters.json
        deploymentName: portal-dev-${{ github.run_number }}

    - name: Get Container App URL
      id: get-url
      run: |
        url=$(az containerapp show \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --query "properties.configuration.ingress.fqdn" \
          --output tsv)
        echo "app-url=https://$url" >> $GITHUB_OUTPUT