name: Deploy to Minikube

on:
  push:
    branches:
      - main  # Change to match the branch for production
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'

jobs:
  deploy:
    runs-on: self-hosted  # Minikube must be accessible here
    environment:
      name: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t jahangir842/portal:${{ github.sha }} .
    
    - name: Push to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jahangir842 --password-stdin
        docker tag jahangir842/portal:${{ github.sha }} jahangir842/portal:latest
        docker push jahangir842/portal:latest
        docker push jahangir842/portal:${{ github.sha }}

    - name: Set up kubectl
      run: |
        minikube update-context
        kubectl get nodes

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl rollout status deployment/portal-app
